// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import HomeOutlined from 'D:/code/y-generator-frontend/node_modules/@ant-design/icons/es/icons/HomeOutlined';
import PlusOutlined from 'D:/code/y-generator-frontend/node_modules/@ant-design/icons/es/icons/PlusOutlined';
import CrownOutlined from 'D:/code/y-generator-frontend/node_modules/@ant-design/icons/es/icons/CrownOutlined';
import TableOutlined from 'D:/code/y-generator-frontend/node_modules/@ant-design/icons/es/icons/TableOutlined';
export default { HomeOutlined, PlusOutlined, CrownOutlined, TableOutlined };
